import type { ClusterResponse, DayRoute, EDAData } from "@/lib/types"

export const MOCK_EDA: EDAData = {
  status: "success",
  stats: {
    total_poi: 6,
    total_stops: 4,
    total_restaurants: 5,
    total_minimarkets: 4,
    total_bus_routes: 2,
  },
  poi_locations: [
    {
      id: 1,
      name: "Monas",
      category: "tourism",
      subcategory: "monument",
      latitude: -6.1754,
      longitude: 106.8272,
      district: "Jakarta Pusat",
    },
    {
      id: 2,
      name: "Museum Nasional",
      category: "historic",
      subcategory: "museum",
      latitude: -6.1766,
      longitude: 106.8227,
      district: "Jakarta Pusat",
    },
    {
      id: 3,
      name: "Taman Suropati",
      category: "leisure",
      subcategory: "park",
      latitude: -6.1991,
      longitude: 106.8328,
      district: "Jakarta Pusat",
    },
    {
      id: 4,
      name: "Kota Tua",
      category: "tourism",
      subcategory: "heritage",
      latitude: -6.1352,
      longitude: 106.8133,
      district: "Jakarta Barat",
    },
    {
      id: 5,
      name: "Ancol",
      category: "tourism",
      subcategory: "theme_park",
      latitude: -6.1256,
      longitude: 106.8367,
      district: "Jakarta Utara",
    },
    {
      id: 6,
      name: "TMII",
      category: "tourism",
      subcategory: "park",
      latitude: -6.3022,
      longitude: 106.8951,
      district: "Jakarta Timur",
    },
  ],
  stop_locations: [
    { stop_name: "Monas", stop_lat: -6.1758, stop_lon: 106.827 },
    { stop_name: "Harmoni", stop_lat: -6.1663, stop_lon: 106.8253 },
    { stop_name: "Kota", stop_lat: -6.1377, stop_lon: 106.8146 },
    { stop_name: "Cawang", stop_lat: -6.2423, stop_lon: 106.8674 },
  ],
  restaurant_locations: [
    { name: "Resto A", latitude: -6.1762, longitude: 106.8263 },
    { name: "Resto B", latitude: -6.1775, longitude: 106.8233 },
    { name: "Resto C", latitude: -6.1988, longitude: 106.8338 },
    { name: "Resto D", latitude: -6.1361, longitude: 106.8142 },
    { name: "Resto E", latitude: -6.302, longitude: 106.8944 },
  ],
  minimarket_locations: [
    { name: "Mini A", latitude: -6.1759, longitude: 106.8266 },
    { name: "Mini B", latitude: -6.1994, longitude: 106.8319 },
    { name: "Mini C", latitude: -6.1358, longitude: 106.8129 },
    { name: "Mini D", latitude: -6.3028, longitude: 106.8956 },
  ],
  poi_by_category: [
    { category: "tourism", count: 4 },
    { category: "historic", count: 1 },
    { category: "leisure", count: 1 },
  ],
  poi_by_district: [
    { district: "Jakarta Pusat", count: 3 },
    { district: "Jakarta Barat", count: 1 },
    { district: "Jakarta Utara", count: 1 },
    { district: "Jakarta Timur", count: 1 },
  ],
  poi_missing_coordinates: 0,
  poi_density_grid: [
    {
      cell_id: "-619:10682",
      lat_min: -6.19,
      lat_max: -6.18,
      lon_min: 106.82,
      lon_max: 106.83,
      center_lat: -6.185,
      center_lon: 106.825,
      count: 2,
      intensity: 1,
    },
    {
      cell_id: "-614:10681",
      lat_min: -6.14,
      lat_max: -6.13,
      lon_min: 106.81,
      lon_max: 106.82,
      center_lat: -6.135,
      center_lon: 106.815,
      count: 1,
      intensity: 0.5,
    },
  ],
  district_details: [
    {
      district: "Jakarta Pusat",
      poi_count: 3,
      centroid_lat: -6.1837,
      centroid_lon: 106.8276,
      poi_density_index: 0.5,
      nearest_stop_distance_m: 202.4,
    },
    {
      district: "Jakarta Barat",
      poi_count: 1,
      centroid_lat: -6.1352,
      centroid_lon: 106.8133,
      poi_density_index: 0.1667,
      nearest_stop_distance_m: 184.3,
    },
    {
      district: "Jakarta Utara",
      poi_count: 1,
      centroid_lat: -6.1256,
      centroid_lon: 106.8367,
      poi_density_index: 0.1667,
      nearest_stop_distance_m: 1325.5,
    },
    {
      district: "Jakarta Timur",
      poi_count: 1,
      centroid_lat: -6.3022,
      centroid_lon: 106.8951,
      poi_density_index: 0.1667,
      nearest_stop_distance_m: 3278.8,
    },
  ],
  coordinate_bounds: {
    min_lat: -6.3028,
    max_lat: -6.1256,
    min_lon: 106.8129,
    max_lon: 106.8956,
  },
  spatial_insights: {
    district_coverage: 4,
    coordinate_completeness_pct: 100,
    avg_nearest_stop_distance_m: 1247.75,
    densest_district: {
      district: "Jakarta Pusat",
      poi_count: 3,
      centroid_lat: -6.1837,
      centroid_lon: 106.8276,
      poi_density_index: 0.5,
      nearest_stop_distance_m: 202.4,
    },
    sparsest_district: {
      district: "Jakarta Timur",
      poi_count: 1,
      centroid_lat: -6.3022,
      centroid_lon: 106.8951,
      poi_density_index: 0.1667,
      nearest_stop_distance_m: 3278.8,
    },
  },
  bus_route_lines: [
    {
      route_id: "R1",
      route_name: "Koridor 1",
      route_short_name: "1",
      route_long_name: "Blok M - Kota",
      route_type: 3,
      route_type_label: "Bus",
      line_color: "#1D4ED8",
      shape_id: "shape_r1",
      points: [
        [-6.2448, 106.8001],
        [-6.225, 106.815],
        [-6.195, 106.822],
        [-6.1702, 106.8262],
        [-6.1378, 106.8146],
      ],
    },
    {
      route_id: "R2",
      route_name: "Koridor 9",
      route_short_name: "9",
      route_long_name: "Pinang Ranti - Pluit",
      route_type: 11,
      route_type_label: "Trolleybus",
      line_color: "#9333EA",
      shape_id: "shape_r2",
      points: [
        [-6.291, 106.878],
        [-6.255, 106.86],
        [-6.215, 106.84],
        [-6.175, 106.827],
        [-6.125, 106.81],
      ],
    },
  ],
  bus_route_type_summary: [
    { route_type: 3, label: "Bus", count: 1 },
    { route_type: 11, label: "Trolleybus", count: 1 },
  ],
  gtfs_source_folder: "e:\\app\\mdb-1909-202602150020",
}

export const MOCK_CLUSTER_RESPONSE: ClusterResponse = {
  status: "success",
  clusters: {
    "0": {
      day: 1,
      pois: [
        {
          poi_id: 1,
          name: "Monas",
          category: "tourism",
          subcategory: "monument",
          latitude: -6.1754,
          longitude: 106.8272,
          description: "Monumen Nasional di pusat Jakarta.",
          district: "Jakarta Pusat",
          semantic_score: 0.91,
          dist_to_hotel_m: 2400,
          dist_to_stop_m: 180,
          resto_count: 5,
          minimarket_count: 3,
        },
        {
          poi_id: 2,
          name: "Museum Nasional",
          category: "historic",
          subcategory: "museum",
          latitude: -6.1766,
          longitude: 106.8227,
          description: "Museum bersejarah koleksi nasional.",
          district: "Jakarta Pusat",
          semantic_score: 0.88,
          dist_to_hotel_m: 2100,
          dist_to_stop_m: 140,
          resto_count: 6,
          minimarket_count: 2,
        },
      ],
      summary: {
        member_count: 2,
        avg_semantic_score: 0.895,
        avg_dist_to_hotel_m: 1700,
        avg_dist_to_stop_m: 160,
        avg_resto_count: 5.5,
        dominant_category: "museum",
      },
    },
    "1": {
      day: 2,
      pois: [
        {
          poi_id: 4,
          name: "Kota Tua",
          category: "tourism",
          subcategory: "heritage",
          latitude: -6.1352,
          longitude: 106.8133,
          description: "Kawasan heritage bersejarah Batavia.",
          district: "Jakarta Barat",
          semantic_score: 0.82,
          dist_to_hotel_m: 6300,
          dist_to_stop_m: 320,
          resto_count: 4,
          minimarket_count: 2,
        },
        {
          poi_id: 5,
          name: "Ancol",
          category: "tourism",
          subcategory: "theme_park",
          latitude: -6.1256,
          longitude: 106.8367,
          description: "Kawasan wisata pantai dan hiburan.",
          district: "Jakarta Utara",
          semantic_score: 0.79,
          dist_to_hotel_m: 7800,
          dist_to_stop_m: 850,
          resto_count: 7,
          minimarket_count: 4,
        },
      ],
      summary: {
        member_count: 2,
        avg_semantic_score: 0.805,
        avg_dist_to_hotel_m: 7050,
        avg_dist_to_stop_m: 585,
        avg_resto_count: 5.5,
        dominant_category: "heritage",
      },
    },
  },
  evaluation: {
    silhouette_score: 0.6123,
    davies_bouldin_index: 0.7241,
    wcss: 2.3911,
    k_optimal: 2,
    iterations: 9,
  },
  k_analysis: {
    k_range: [2, 3, 4],
    wcss_values: [2.3911, 1.9804, 1.5407],
    silhouette_values: [0.6123, 0.5844, 0.5098],
  },
}

export const MOCK_ROUTES: Record<string, DayRoute> = {
  "0": {
    status: "success",
    day: 1,
    hotel: { lat: -6.2088, lon: 106.8456 },
    ordered_route: [
      {
        order: 1,
        poi_id: 1,
        name: "Monas",
        latitude: -6.1754,
        longitude: 106.8272,
        distance_from_prev_m: 4100,
        distance_from_prev_km: 4.1,
      },
      {
        order: 2,
        poi_id: 2,
        name: "Museum Nasional",
        latitude: -6.1766,
        longitude: 106.8227,
        distance_from_prev_m: 520,
        distance_from_prev_km: 0.52,
      },
    ],
    total_distance_km: 4.62,
    total_distance_m: 4620,
  },
  "1": {
    status: "success",
    day: 2,
    hotel: { lat: -6.2088, lon: 106.8456 },
    ordered_route: [
      {
        order: 1,
        poi_id: 4,
        name: "Kota Tua",
        latitude: -6.1352,
        longitude: 106.8133,
        distance_from_prev_m: 9400,
        distance_from_prev_km: 9.4,
      },
      {
        order: 2,
        poi_id: 5,
        name: "Ancol",
        latitude: -6.1256,
        longitude: 106.8367,
        distance_from_prev_m: 2700,
        distance_from_prev_km: 2.7,
      },
    ],
    total_distance_km: 12.1,
    total_distance_m: 12100,
  },
}
